# Generated by Django 4.1.7 on 2023-05-29 17:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_ufr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name_plural': 'Commune',
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150, unique=True, verbose_name='Libellé')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('contact', models.CharField(max_length=100, unique=True, verbose_name='Contact')),
            ],
            options={
                'verbose_name_plural': 'Filière',
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150, unique=True, verbose_name='Libellé')),
            ],
            options={
                'verbose_name_plural': 'Niveau',
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name_plural': 'Ville',
            },
        ),
        migrations.AlterField(
            model_name='ufr',
            name='libelle',
            field=models.CharField(max_length=150, unique=True, verbose_name='Libellé'),
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150, unique=True, verbose_name='Libellé')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.filiere', verbose_name='Filière')),
            ],
            options={
                'verbose_name_plural': 'Specialité',
            },
        ),
        migrations.CreateModel(
            name='NiveauSpecialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.niveau', verbose_name='Niveau')),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.specialite', verbose_name='Specialité')),
            ],
            options={
                'verbose_name_plural': 'Niveau et Specialité',
            },
        ),
        migrations.AddField(
            model_name='filiere',
            name='ufr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ufr', verbose_name='ufr'),
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénoms')),
                ('lieu_nais', models.CharField(max_length=100, verbose_name='Lieu de naissance')),
                ('date_nais', models.DateField(verbose_name='Date de naissance')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('contact', models.CharField(max_length=100, unique=True, verbose_name='Téléphone')),
                ('matricule', models.CharField(max_length=100, unique=True, verbose_name="N° de carte d'étudiant")),
                ('cni', models.CharField(max_length=100, unique=True, verbose_name='N° CNI')),
                ('carte_etudiant', models.FileField(upload_to='carte_etudiant', verbose_name="Carte d'etudiant")),
                ('carte_cni', models.FileField(upload_to='cni', verbose_name='Carte CNI')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'identification")),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.commune', verbose_name='Commune')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.filiere', verbose_name='Filière')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.niveau', verbose_name='Niveau')),
                ('sexe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.sexe', verbose_name='Sexe')),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.specialite', verbose_name='Specialité')),
                ('ufr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ufr', verbose_name='UFR')),
                ('universite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.universite', verbose_name='Université')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ville', verbose_name='Ville')),
            ],
            options={
                'verbose_name_plural': 'Etudiant',
            },
        ),
        migrations.AddField(
            model_name='commune',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ville', verbose_name='Ville'),
        ),
    ]
