# Generated by Django 4.1.7 on 2023-05-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_commune_filiere_niveau_ville_alter_ufr_libelle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='cni',
            field=models.CharField(max_length=15, unique=True, verbose_name='N° CNI'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='matricule',
            field=models.CharField(max_length=15, unique=True, verbose_name="N° de carte d'étudiant"),
        ),
    ]
