# Generated by Django 4.1.7 on 2023-05-31 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_etudiant_cni_alter_etudiant_matricule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filiere',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='filiere',
            name='email',
        ),
    ]
